### ISSUE TITLE
HUD/GUI Dialogue Bubbles Show Wrong M&L Partners In Time

### ISSUE THREAD

**Issue by Iteasl569** [melonDS-emu/melonDS#1701]
As stated, the game's dialogue runs perfectly outside of battle but in battle it doesn't render on top of the text boxes AND the text boxes themselves aren't in the right place. Please help.

![Pokémon_Shining_Pearl_20230614_181355_00](https://github.com/melonDS-emu/melonDS/assets/119144146/0d3ae324-5d06-4b92-aae6-ffcfda5d001e)
![Pokémon_Shining_Pearl_20230614_181339_00](https://github.com/melonDS-emu/melonDS/assets/119144146/9b9689a0-1112-4e42-8a81-0e38d1159861)
![Pokémon_Shining_Pearl_20230614_181328_00](https://github.com/melonDS-emu/melonDS/assets/119144146/bb3bc2d9-e657-492c-926c-3a6a846216cc)

![Pokémon_Shining_Pearl_20230614_181332_00](https://github.com/melonDS-emu/melonDS/assets/119144146/8db933d1-535d-4bbf-ac89-86a3fdaeffcc)

![Pokémon_Shining_Pearl_20230614_181336_00](https://github.com/melonDS-emu/melonDS/assets/119144146/7d0a71ee-251b-424f-b294-e0fb89cd748c)

**Comment by RSDuck** [comment]
I just fixed this bug in the compute shader renderer a short while ago. Do you use it.

**Comment by Iteasl569** [comment]
> I just fixed this bug in the compute shader renderer a short while ago. Do you use it.

Oh I forgot to mention this is on the switch homebrew port of the emulator. I apologize.

**Comment by RSDuck** [comment]
yeah it's using the compute shader renderer, so it's fixed.

**Comment by Iteasl569** [comment]
> yeah it's using the compute shader renderer, so it's fixed.

But it's still happening on my switch? Is the updated version posted in the HB app store or do I have to download it from GitHub?

**Comment by Iteasl569** [comment]
> it's not yet in any release.

do you have an eta when a release will be available?
