### ISSUE TITLE
Dragon Quest 9 Canvass (also known as Tag or StreetPass)'s crash issue

### ISSUE THREAD

**Issue by MelonGx** [melonDS-emu/melonDS#646]
(1) Load DQ9 with melonDS
(2) Start a canvass
(3) Leave it for minutes or hours

The game will crash if I leave it in canvass mode too long (over 15 minutes).
But if I use real DS/DSi/3DS console, the crash will never happen even I leave it in canvass mode 24 hours.

**Comment by MelonGx** [comment]
BTW is it available to use multi-core for melonDS? 
Only single core of my i7-9700K works even I opened 3 or more melonDS processes.

**Comment by RSDuck** [comment]
can you provide us with a savefile? Also please name the region of the rom.

> BTW is it available to use multi-core for melonDS?
Only single core of my i7-9700K works even I opened 3 or more melonDS processes.

melonDS can only utilise a single core per instance, or two if you use the threaded software renderer. That multiple processes don't end up on multiple cores is weird, though there's nothing we can do about it.

**Comment by MelonGx** [comment]
It happens on every region (JP US EU) and any proper save.
Just go to Stornway’s Inn and start a canvass, then leave it open for over 15 mins. Then this crash issue can be reproduced.

**Comment by RSDuck** [comment]
I've never played Dragon Quest and I don't want to sit through the first whatever minutes of intro and tutorial to reproduce the bug.

**Comment by cookiestar446** [comment]
here i have made a test save file for Dragon Quest IX - Sentinels of the Starry Skies (Europe)
its a quicksave so you are right in front of the NPC

btw as a newbie to dq9 you would take 1/2 - 2 hour to get to Stornway ...

[Dragon Quest IX - Sentinels of the Starry Skies.zip](https://github.com/Arisotura/melonDS/files/4766204/Dragon.Quest.IX.-.Sentinels.of.the.Starry.Skies.zip)

**Comment by MelonGx** [comment]
I just wanted to say this crash happened on every save regardless of the game progress and whether it was hacked or not. 
If you just want to reproduce the issue easier, then every 64KB saves in the following link should be OK.
https://www.woodus.com/den/games/dq9ds/savefiles.php

**Comment by RSDuck** [comment]
thanks for the savefile, I hope my last comment didn't came off as too snarky.

I've been running it for quite some time, but couldn't reproduce it. Maybe it was already fixed since the last stable versions?

**Comment by cookiestar446** [comment]
i have no problem either. running over 6 hours now
version 0.8.3

**Comment by MelonGx** [comment]
Oh, I just found that the issue happened on 0.8.2.
Just reproduced this issue on 0.8.2.
I'll try it on 0.8.3 one more time.
![無題](https://user-images.githubusercontent.com/7697767/84447272-85e00b00-ac82-11ea-9889-52677fac5ba5.png)

**Comment by MelonGx** [comment]
Uh oh, it's still happening on 0.8.3 here.
![無題](https://user-images.githubusercontent.com/7697767/84447689-abb9df80-ac83-11ea-8eef-e0f5fc24ae2b.png)

**Comment by RSDuck** [comment]
good to know, I only tried it without connecting another game.

Looks like this is an issue with local wireless, which known to be unstable. Though usually it results in connection errors as far as I know.

**Comment by cookiestar446** [comment]
now i get this error too

after 5 min client 4 got the message and just 3 min later client 1
i even tested it with just 2 clients. same result
![TEST1](https://user-images.githubusercontent.com/66794484/84454081-e4dd5a00-ac59-11ea-8188-6259cd0d8edf.jpg)
![TEST2](https://user-images.githubusercontent.com/66794484/84454095-eeff5880-ac59-11ea-84a4-fc8c9257672f.jpg)
![TEST3](https://user-images.githubusercontent.com/66794484/84454116-f7f02a00-ac59-11ea-85a7-622683ce7dde.jpg)


@MelonGx your text is a little bit misleading **`The game will crash if I leave it in canvass mode too long`** i expected that melonDS just close or something like that.

wifi at this state is currently not very usable.
i got DQ9 local Multiplayer with 2 client some times running fine for few hours
sometimes i get an error after few minutes.
but when a 3rd client try to connect its kick all out immediately.

**Comment by MojoJojoDojo** [comment]
Kingdom Hearts recoded also had a Tag mode and I think it got similar issues as well.

**Comment by KostaSaizo7** [comment]
Probably fixed by https://github.com/melonDS-emu/melonDS/pull/1516

I guess the 3rd instance detected only one guest because I use the same savefile in the first two instances.

![Dragon quest 9 canvass](https://user-images.githubusercontent.com/39852873/192130016-d8d21373-8532-4e1f-bd87-1cd1f6c40e2f.png)
![Dragon quest 9 canvass b](https://user-images.githubusercontent.com/39852873/192130103-5951ab05-6a44-45b8-9bc9-7b70a9eebde1.png)
